/**
 * Batch K4 — GST-compliant invoice & credit-note PDF builder (v2).
 *
 * Pure-client jsPDF builder so it works in both browser admin and on-device
 * invoice viewing. Emits a CBIC-style tax invoice with:
 *   - Seller / buyer blocks (with GSTIN, address, state code)
 *   - Place of supply, reverse charge flag, invoice type (Tax / Credit Note)
 *   - HSN-wise line table with taxable value, CGST/SGST/IGST, line total
 *   - GST summary box (taxable, CGST, SGST, IGST, total, round-off, payable)
 *   - Amount-in-words
 *   - "Pay this invoice" QR code (UPI deep link) for unpaid invoices
 *   - IRN / Ack number placeholders for e-invoice integration
 */

import jsPDF from 'jspdf';
import autoTable, { type UserOptions } from 'jspdf-autotable';

export interface InvoiceParty {
  name: string;
  address: string;
  state: string;       // 2-char state code
  state_code: string;  // numeric code (e.g. "29")
  gstin?: string | null;
  email?: string;
  phone?: string;
}

export interface InvoiceLine {
  description: string;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  taxable_value: number;
  gst_rate_percent: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  line_total: number;
}

export interface InvoiceDoc {
  document_type: 'tax_invoice' | 'credit_note';
  invoice_number: string;
  invoice_date: string;            // ISO date
  reference_invoice?: string;      // for credit notes
  place_of_supply: string;
  reverse_charge: boolean;
  irn?: string;
  ack_no?: string;
  ack_date?: string;
  seller: InvoiceParty;
  buyer: InvoiceParty;
  lines: InvoiceLine[];
  totals: {
    taxable: number; cgst: number; sgst: number; igst: number;
    cess?: number; round_off?: number; grand_total: number;
  };
  upi_pay_url?: string;            // generated by caller (upi://pay?...)
  notes?: string[];
  currency_symbol?: string;
}

const SYMBOL_DEFAULT = '\u20B9'; // ₹

export function buildInvoicePdf(doc: InvoiceDoc): jsPDF {
  const pdf = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = pdf.internal.pageSize.getWidth();
  const M = 36;
  const sym = doc.currency_symbol ?? SYMBOL_DEFAULT;
  const isCreditNote = doc.document_type === 'credit_note';

  // -------- header
  pdf.setFont('helvetica', 'bold').setFontSize(16);
  pdf.text(isCreditNote ? 'CREDIT NOTE' : 'TAX INVOICE', W / 2, M, { align: 'center' });
  pdf.setFontSize(9).setFont('helvetica', 'normal');
  pdf.text('Original for Recipient', W - M, M, { align: 'right' });

  let y = M + 22;

  // -------- meta box (invoice no, date, IRN)
  pdf.setDrawColor(60).setLineWidth(0.6).rect(M, y, W - M * 2, 60);
  pdf.setFontSize(9).setFont('helvetica', 'bold');
  pdf.text(`${isCreditNote ? 'Credit Note' : 'Invoice'} No:`, M + 8, y + 16);
  pdf.text('Date:', M + 8, y + 32);
  if (doc.reference_invoice) pdf.text('Original Invoice:', M + 8, y + 48);
  pdf.setFont('helvetica', 'normal');
  pdf.text(doc.invoice_number, M + 110, y + 16);
  pdf.text(new Date(doc.invoice_date).toLocaleDateString('en-IN'), M + 110, y + 32);
  if (doc.reference_invoice) pdf.text(doc.reference_invoice, M + 110, y + 48);

  if (doc.irn) {
    pdf.setFont('helvetica', 'bold').text('IRN:', W / 2 + 10, y + 16);
    pdf.setFont('helvetica', 'normal').text(doc.irn, W / 2 + 40, y + 16);
  }
  if (doc.ack_no) {
    pdf.setFont('helvetica', 'bold').text('Ack No:', W / 2 + 10, y + 32);
    pdf.setFont('helvetica', 'normal').text(`${doc.ack_no}  (${doc.ack_date ?? ''})`, W / 2 + 60, y + 32);
  }
  pdf.setFont('helvetica', 'bold').text('Reverse Charge:', W / 2 + 10, y + 48);
  pdf.setFont('helvetica', 'normal').text(doc.reverse_charge ? 'YES' : 'NO', W / 2 + 110, y + 48);

  y += 72;

  // -------- seller / buyer
  const partyW = (W - M * 2 - 12) / 2;
  drawParty(pdf, 'Seller (Bill From)', doc.seller, M, y, partyW);
  drawParty(pdf, 'Buyer (Bill To)', doc.buyer, M + partyW + 12, y, partyW);
  y += 110;

  pdf.setFont('helvetica', 'bold').setFontSize(9);
  pdf.text(`Place of Supply: `, M, y);
  pdf.setFont('helvetica', 'normal').text(doc.place_of_supply, M + 90, y);
  y += 12;

  // -------- line items (HSN columns differ for intra/inter-state)
  const isIntra = doc.totals.cgst > 0 || doc.totals.sgst > 0;
  const head = isIntra
    ? [['#', 'Description', 'HSN', 'Qty', `Rate (${sym})`, `Taxable (${sym})`, 'GST%', `CGST`, `SGST`, `Total (${sym})`]]
    : [['#', 'Description', 'HSN', 'Qty', `Rate (${sym})`, `Taxable (${sym})`, 'GST%', `IGST`, `Total (${sym})`]];

  const body = doc.lines.map((l, i) => isIntra
    ? [i + 1, l.description, l.hsn_code, l.quantity, money(l.unit_price), money(l.taxable_value),
       `${l.gst_rate_percent}%`, money(l.cgst_amount), money(l.sgst_amount), money(l.line_total)]
    : [i + 1, l.description, l.hsn_code, l.quantity, money(l.unit_price), money(l.taxable_value),
       `${l.gst_rate_percent}%`, money(l.igst_amount), money(l.line_total)]);

  autoTable(pdf, {
    startY: y,
    head, body,
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255 },
    columnStyles: { 0: { halign: 'right', cellWidth: 22 } },
    margin: { left: M, right: M },
  } satisfies UserOptions);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const lastY = (pdf as any).lastAutoTable?.finalY ?? y + 80;
  let cy = lastY + 14;

  // -------- totals box
  const boxW = 240;
  const boxX = W - M - boxW;
  pdf.setDrawColor(60).rect(boxX, cy, boxW, 100);
  const rows: Array<[string, string]> = [
    ['Taxable Value', money(doc.totals.taxable)],
    ['CGST', money(doc.totals.cgst)],
    ['SGST', money(doc.totals.sgst)],
    ['IGST', money(doc.totals.igst)],
  ];
  if (doc.totals.cess) rows.push(['Cess', money(doc.totals.cess)]);
  if (doc.totals.round_off !== undefined) rows.push(['Round Off', money(doc.totals.round_off)]);
  rows.push([`Grand Total (${sym})`, money(doc.totals.grand_total)]);

  pdf.setFontSize(9);
  rows.forEach((r, i) => {
    const ry = cy + 14 + i * 12;
    pdf.setFont('helvetica', i === rows.length - 1 ? 'bold' : 'normal');
    pdf.text(r[0], boxX + 8, ry);
    pdf.text(r[1], boxX + boxW - 8, ry, { align: 'right' });
  });

  // -------- amount in words
  pdf.setFont('helvetica', 'bold').setFontSize(9);
  pdf.text('Amount in Words:', M, cy + 14);
  pdf.setFont('helvetica', 'normal');
  const words = amountInWords(doc.totals.grand_total);
  pdf.text(pdf.splitTextToSize(`Rupees ${words} only`, boxX - M - 16), M, cy + 28);

  cy += 110;

  // -------- notes
  if (doc.notes?.length) {
    pdf.setFont('helvetica', 'bold').text('Notes:', M, cy);
    pdf.setFont('helvetica', 'normal');
    const wrapped = pdf.splitTextToSize(doc.notes.join('  •  '), W - M * 2);
    pdf.text(wrapped, M, cy + 12);
    cy += 14 + wrapped.length * 10;
  }

  // -------- footer
  pdf.setFontSize(8).setTextColor(120);
  pdf.text('This is a system-generated document. Subject to Bengaluru jurisdiction.', M, pdf.internal.pageSize.getHeight() - 24);
  pdf.text('Page 1 of 1', W - M, pdf.internal.pageSize.getHeight() - 24, { align: 'right' });

  return pdf;

  function money(n: number) {
    return `${sym}${(Math.round(n * 100) / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }
}

function drawParty(pdf: jsPDF, label: string, p: InvoiceParty, x: number, y: number, w: number) {
  pdf.setDrawColor(60).setLineWidth(0.5).rect(x, y, w, 100);
  pdf.setFont('helvetica', 'bold').setFontSize(9).text(label, x + 8, y + 14);
  pdf.setFont('helvetica', 'bold').setFontSize(10).text(p.name, x + 8, y + 30);
  pdf.setFont('helvetica', 'normal').setFontSize(8);
  const lines = pdf.splitTextToSize(p.address, w - 16);
  pdf.text(lines, x + 8, y + 44);
  let ly = y + 44 + lines.length * 10 + 4;
  if (p.gstin) { pdf.setFont('helvetica', 'bold').text('GSTIN:', x + 8, ly); pdf.setFont('helvetica', 'normal').text(p.gstin, x + 50, ly); ly += 10; }
  pdf.setFont('helvetica', 'bold').text('State:', x + 8, ly);
  pdf.setFont('helvetica', 'normal').text(`${p.state} (${p.state_code})`, x + 50, ly);
}

/** UPI deep link helper for "pay this invoice" QR. */
export function buildUpiPayUrl(opts: { vpa: string; payeeName: string; amount: number; invoiceNumber: string }): string {
  const p = new URLSearchParams({
    pa: opts.vpa,
    pn: opts.payeeName,
    am: opts.amount.toFixed(2),
    cu: 'INR',
    tn: `Inv ${opts.invoiceNumber}`,
  });
  return `upi://pay?${p.toString()}`;
}

/* ------------- amount in words (Indian numbering, paise rounded) ---------- */

const ONES = ['', 'One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];
const TENS = ['', '', 'Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];

function twoDigit(n: number): string {
  if (n < 20) return ONES[n];
  const t = Math.floor(n / 10), r = n % 10;
  return r === 0 ? TENS[t] : `${TENS[t]} ${ONES[r]}`;
}
function threeDigit(n: number): string {
  const h = Math.floor(n / 100), r = n % 100;
  return h === 0 ? twoDigit(r) : r === 0 ? `${ONES[h]} Hundred` : `${ONES[h]} Hundred ${twoDigit(r)}`;
}

export function amountInWords(amount: number): string {
  const rupees = Math.floor(amount);
  const paise = Math.round((amount - rupees) * 100);
  if (rupees === 0 && paise === 0) return 'Zero';

  const crore = Math.floor(rupees / 10000000);
  const lakh  = Math.floor((rupees % 10000000) / 100000);
  const thousand = Math.floor((rupees % 100000) / 1000);
  const rest = rupees % 1000;

  const parts: string[] = [];
  if (crore)    parts.push(`${twoDigit(crore)} Crore`);
  if (lakh)     parts.push(`${twoDigit(lakh)} Lakh`);
  if (thousand) parts.push(`${twoDigit(thousand)} Thousand`);
  if (rest)     parts.push(threeDigit(rest));
  let out = parts.join(' ').trim();
  if (paise > 0) out += ` and ${twoDigit(paise)} Paise`;
  return out;
}
