import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export interface Dispute {
  id: string;
  dispute_number: string;
  order_id: string | null;
  sub_order_id: string | null;
  return_request_id: string | null;
  raised_by_type: 'customer' | 'vendor' | 'admin';
  raised_by_id: string;
  vendor_id: string | null;
  dispute_type: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: string;
  title: string;
  description: string;
  evidence_urls: string[] | null;
  resolution_type: string | null;
  resolution_notes: string | null;
  resolution_amount: number | null;
  assigned_to: string | null;
  escalated_at: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface DisputeMessage {
  id: string;
  dispute_id: string;
  sender_id: string;
  sender_type: 'customer' | 'vendor' | 'admin';
  message: string;
  attachments: string[] | null;
  is_internal: boolean;
  created_at: string;
}

export interface CreateDisputeData {
  order_id?: string;
  sub_order_id?: string;
  return_request_id?: string;
  vendor_id?: string;
  dispute_type: string;
  priority?: 'low' | 'medium' | 'high' | 'urgent';
  title: string;
  description: string;
  evidence_urls?: string[];
}

export function useDisputes() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['disputes', user?.id],
    queryFn: async () => {
      if (!user) return [];

      const { data, error } = await supabase
        .from('disputes')
        .select('*')
        .eq('raised_by_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });
}

export function useDispute(disputeId: string | undefined) {
  return useQuery({
    queryKey: ['dispute', disputeId],
    queryFn: async () => {
      if (!disputeId) return null;

      const { data: dispute, error } = await supabase
        .from('disputes')
        .select(`
          *,
          orders(order_number),
          vendors(brand_name)
        `)
        .eq('id', disputeId)
        .single();

      if (error) throw error;

      // Fetch messages
      const { data: messages } = await supabase
        .from('dispute_messages')
        .select('*')
        .eq('dispute_id', disputeId)
        .order('created_at', { ascending: true });

      return { ...dispute, messages: messages || [] };
    },
    enabled: !!disputeId,
  });
}

export function useCreateDispute() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CreateDisputeData) => {
      if (!user) throw new Error('Not authenticated');

      // Determine raised_by_type
      const { data: roles } = await supabase
        .from('user_roles')
        .select('role')
        .eq('user_id', user.id);

      let raisedByType: 'customer' | 'vendor' | 'admin' = 'customer';
      if (roles?.some(r => r.role === 'admin')) {
        raisedByType = 'admin';
      } else if (roles?.some(r => r.role === 'vendor')) {
        raisedByType = 'vendor';
      }

      // dispute_number is auto-generated by trigger
      const { data: dispute, error } = await supabase
        .from('disputes')
        .insert({
          dispute_number: '', // Will be auto-generated by trigger
          dispute_type: data.dispute_type,
          title: data.title,
          description: data.description,
          order_id: data.order_id,
          sub_order_id: data.sub_order_id,
          return_request_id: data.return_request_id,
          vendor_id: data.vendor_id,
          evidence_urls: data.evidence_urls,
          raised_by_type: raisedByType as any,
          raised_by_id: user.id,
          priority: (data.priority || 'medium') as any,
        } as any)
        .select()
        .single();

      if (error) throw error;
      return dispute;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['disputes'] });
      toast.success('Dispute raised successfully');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to raise dispute');
    },
  });
}

export function useSendDisputeMessage() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ 
      disputeId, 
      message, 
      attachments,
      isInternal = false,
    }: { 
      disputeId: string; 
      message: string;
      attachments?: string[];
      isInternal?: boolean;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Determine sender_type
      const { data: roles } = await supabase
        .from('user_roles')
        .select('role')
        .eq('user_id', user.id);

      let senderType: 'customer' | 'vendor' | 'admin' = 'customer';
      if (roles?.some(r => r.role === 'admin')) {
        senderType = 'admin';
      } else if (roles?.some(r => r.role === 'vendor')) {
        senderType = 'vendor';
      }

      const { data, error } = await supabase
        .from('dispute_messages')
        .insert({
          dispute_id: disputeId,
          sender_id: user.id,
          sender_type: senderType,
          message,
          attachments,
          is_internal: isInternal && senderType === 'admin',
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['dispute', variables.disputeId] });
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to send message');
    },
  });
}

export function useVendorDisputes() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['vendor-disputes', user?.id],
    queryFn: async () => {
      if (!user) return [];

      // Get vendor ID
      const { data: vendor } = await supabase
        .from('vendors')
        .select('id')
        .eq('user_id', user.id)
        .single();

      if (!vendor) return [];

      const { data, error } = await supabase
        .from('disputes')
        .select(`
          *,
          orders(order_number)
        `)
        .or(`vendor_id.eq.${vendor.id},raised_by_id.eq.${user.id}`)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });
}

export function useAdminDisputes() {
  return useQuery({
    queryKey: ['admin-disputes'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('disputes')
        .select(`
          *,
          orders(order_number),
          vendors(brand_name)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
  });
}

export function useUpdateDispute() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ 
      disputeId, 
      updates 
    }: { 
      disputeId: string; 
      updates: Partial<Dispute>; 
    }) => {
      const { data, error } = await supabase
        .from('disputes')
        .update(updates)
        .eq('id', disputeId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['disputes'] });
      queryClient.invalidateQueries({ queryKey: ['dispute', variables.disputeId] });
      queryClient.invalidateQueries({ queryKey: ['vendor-disputes'] });
      queryClient.invalidateQueries({ queryKey: ['admin-disputes'] });
      toast.success('Dispute updated');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to update dispute');
    },
  });
}
