import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export interface ReturnRequest {
  id: string;
  return_number: string;
  order_id: string;
  sub_order_id: string;
  customer_id: string;
  vendor_id: string;
  status: string;
  return_reason: string;
  return_reason_details: string | null;
  images: string[] | null;
  refund_amount: number | null;
  refund_method: string | null;
  pickup_address: Record<string, any> | null;
  pickup_awb: string | null;
  pickup_scheduled_at: string | null;
  picked_up_at: string | null;
  received_at: string | null;
  inspected_at: string | null;
  inspection_notes: string | null;
  inspection_result: string | null;
  admin_notes: string | null;
  vendor_notes: string | null;
  approved_at: string | null;
  rejected_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface ReturnItem {
  id: string;
  return_request_id: string;
  order_item_id: string;
  quantity: number;
  reason: string | null;
  refund_amount: number | null;
}

export interface CreateReturnData {
  order_id: string;
  sub_order_id: string;
  vendor_id: string;
  return_reason: string;
  return_reason_details?: string;
  images?: string[];
  items: {
    order_item_id: string;
    quantity: number;
    reason?: string;
  }[];
  pickup_address?: Record<string, any>;
}

export function useReturns() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['returns', user?.id],
    queryFn: async () => {
      if (!user) return [];

      const { data, error } = await supabase
        .from('return_requests')
        .select('*')
        .eq('customer_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });
}

export function useReturnRequest(returnId: string | undefined) {
  return useQuery({
    queryKey: ['return', returnId],
    queryFn: async () => {
      if (!returnId) return null;

      const { data: returnRequest, error } = await supabase
        .from('return_requests')
        .select('*')
        .eq('id', returnId)
        .single();

      if (error) throw error;

      // Fetch return items
      const { data: items } = await supabase
        .from('return_items')
        .select('*, order_items(product_title, product_image, unit_price)')
        .eq('return_request_id', returnId);

      return { ...returnRequest, items: items || [] };
    },
    enabled: !!returnId,
  });
}

export function useCreateReturn() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CreateReturnData) => {
      if (!user) throw new Error('Not authenticated');

      // Calculate refund amount from items
      const itemIds = data.items.map(i => i.order_item_id);
      const { data: orderItems } = await supabase
        .from('order_items')
        .select('id, unit_price, quantity')
        .in('id', itemIds);

      const refundAmount = data.items.reduce((total, item) => {
        const orderItem = orderItems?.find(oi => oi.id === item.order_item_id);
        return total + (orderItem?.unit_price || 0) * item.quantity;
      }, 0);

      // Create return request - return_number is auto-generated by trigger
      const { data: returnRequest, error } = await supabase
        .from('return_requests')
        .insert({
          return_number: '', // Will be auto-generated by trigger
          order_id: data.order_id,
          sub_order_id: data.sub_order_id,
          customer_id: user.id,
          vendor_id: data.vendor_id,
          return_reason: data.return_reason as any,
          return_reason_details: data.return_reason_details,
          images: data.images,
          refund_amount: refundAmount,
          pickup_address: data.pickup_address,
        } as any)
        .select()
        .single();

      if (error) throw error;

      // Create return items
      const returnItems = data.items.map(item => ({
        return_request_id: returnRequest.id,
        order_item_id: item.order_item_id,
        quantity: item.quantity,
        reason: item.reason,
        refund_amount: (orderItems?.find(oi => oi.id === item.order_item_id)?.unit_price || 0) * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('return_items')
        .insert(returnItems);

      if (itemsError) throw itemsError;

      return returnRequest;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['returns'] });
      toast.success('Return request submitted successfully');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to create return request');
    },
  });
}

export function useVendorReturns() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['vendor-returns', user?.id],
    queryFn: async () => {
      if (!user) return [];

      // Get vendor ID
      const { data: vendor } = await supabase
        .from('vendors')
        .select('id')
        .eq('user_id', user.id)
        .single();

      if (!vendor) return [];

      const { data, error } = await supabase
        .from('return_requests')
        .select(`
          *,
          orders(order_number),
          return_items(*, order_items(product_title, product_image))
        `)
        .eq('vendor_id', vendor.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });
}

export function useAdminReturns() {
  return useQuery({
    queryKey: ['admin-returns'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('return_requests')
        .select(`
          *,
          orders(order_number, customer_id),
          vendors(brand_name),
          return_items(*, order_items(product_title, product_image))
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
  });
}

export function useUpdateReturn() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ 
      returnId, 
      updates 
    }: { 
      returnId: string; 
      updates: Partial<ReturnRequest>; 
    }) => {
      const { data, error } = await supabase
        .from('return_requests')
        .update(updates)
        .eq('id', returnId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['returns'] });
      queryClient.invalidateQueries({ queryKey: ['vendor-returns'] });
      queryClient.invalidateQueries({ queryKey: ['admin-returns'] });
      toast.success('Return request updated');
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to update return');
    },
  });
}
